# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginHandler.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 460)
        MainWindow.setMinimumSize(QtCore.QSize(560, 360))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginContainer_main = QtWidgets.QFrame(self.centralwidget)
        self.loginContainer_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.loginContainer_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loginContainer_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginContainer_main.setObjectName("loginContainer_main")
        self.verticalLayout_loginContainer_main = QtWidgets.QVBoxLayout(self.loginContainer_main)
        self.verticalLayout_loginContainer_main.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_loginContainer_main.setSpacing(0)
        self.verticalLayout_loginContainer_main.setObjectName("verticalLayout_loginContainer_main")
        self.loginContainer_top = QtWidgets.QFrame(self.loginContainer_main)
        self.loginContainer_top.setStyleSheet("background-color: rgb(39, 44, 54);\n"
"color: white;")
        self.loginContainer_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginContainer_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginContainer_top.setObjectName("loginContainer_top")
        self.horizontalLayout_loginContainer_top = QtWidgets.QHBoxLayout(self.loginContainer_top)
        self.horizontalLayout_loginContainer_top.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_loginContainer_top.setSpacing(0)
        self.horizontalLayout_loginContainer_top.setObjectName("horizontalLayout_loginContainer_top")
        self.qsystem_login_label = QtWidgets.QLabel(self.loginContainer_top)
        self.qsystem_login_label.setStyleSheet("QLabel{\n"
"font: 10pt;\n"
"margin-left: 4px;\n"
"}\n"
"\n"
"\n"
"")
        self.qsystem_login_label.setObjectName("qsystem_login_label")
        self.horizontalLayout_loginContainer_top.addWidget(self.qsystem_login_label)
        self.qsystem_buttons = QtWidgets.QFrame(self.loginContainer_top)
        self.qsystem_buttons.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.qsystem_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qsystem_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qsystem_buttons.setObjectName("qsystem_buttons")
        self.horizontalLayout_qsystem_buttons = QtWidgets.QHBoxLayout(self.qsystem_buttons)
        self.horizontalLayout_qsystem_buttons.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_qsystem_buttons.setSpacing(8)
        self.horizontalLayout_qsystem_buttons.setObjectName("horizontalLayout_qsystem_buttons")
        self.pushButton_2 = QtWidgets.QPushButton(self.qsystem_buttons)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(18, 22))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_qsystem_buttons.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.qsystem_buttons)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(18, 22))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_qsystem_buttons.addWidget(self.pushButton)
        self.horizontalLayout_loginContainer_top.addWidget(self.qsystem_buttons, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_loginContainer_top.setStretch(0, 6)
        self.horizontalLayout_loginContainer_top.setStretch(1, 1)
        self.verticalLayout_loginContainer_main.addWidget(self.loginContainer_top)
        self.loginContainer_bot = QtWidgets.QFrame(self.loginContainer_main)
        self.loginContainer_bot.setStyleSheet("background-color: rgb(53, 59, 73);")
        self.loginContainer_bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginContainer_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginContainer_bot.setObjectName("loginContainer_bot")
        self.verticalLayout_loginContainer_bot = QtWidgets.QVBoxLayout(self.loginContainer_bot)
        self.verticalLayout_loginContainer_bot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_loginContainer_bot.setSpacing(0)
        self.verticalLayout_loginContainer_bot.setObjectName("verticalLayout_loginContainer_bot")
        self.login_stackedWidget = QtWidgets.QStackedWidget(self.loginContainer_bot)
        self.login_stackedWidget.setObjectName("login_stackedWidget")
        self.verticalLayout_loginContainer_bot.addWidget(self.login_stackedWidget)
        self.verticalLayout_loginContainer_main.addWidget(self.loginContainer_bot)
        self.verticalLayout_loginContainer_main.setStretch(0, 1)
        self.verticalLayout_loginContainer_main.setStretch(1, 14)
        self.verticalLayout.addWidget(self.loginContainer_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qsystem_login_label.setText(_translate("MainWindow", "CCS Queue System Login"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
