# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_BASE_v2_faculty.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_top.setStyleSheet("background-color: transparent;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_toggle = QtWidgets.QFrame(self.frame_top)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_toggle.setStyleSheet("background-color: rgb(32,34,67);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_toggle_menu = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu.setSizePolicy(sizePolicy)
        self.btn_toggle_menu.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-menu.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a7ecb;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu.setText("")
        self.btn_toggle_menu.setObjectName("btn_toggle_menu")
        self.verticalLayout_3.addWidget(self.btn_toggle_menu)
        self.horizontalLayout_3.addWidget(self.frame_toggle)
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        self.frame_top_right.setStyleSheet("background: transparent;")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_top_right)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_top_btns.setStyleSheet("background-color: rgba(37,39,77)")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_top_btns.sizePolicy().hasHeightForWidth())
        self.frame_label_top_btns.setSizePolicy(sizePolicy)
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-terminal.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_10.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right.sizePolicy().hasHeightForWidth())
        self.frame_btns_right.setSizePolicy(sizePolicy)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7a7ecb;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_maximize_restore.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_maximize_restore.setStyleSheet("")
        self.btn_maximize_restore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon1)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_5.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setStyleSheet("")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_top_btns)
        self.frame_top_info = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_info.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_top_info.setStyleSheet("background-color: rgba(41,43,83);")
        self.frame_top_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_info.setObjectName("frame_top_info")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_top_info)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_top_info_1 = QtWidgets.QLabel(self.frame_top_info)
        self.label_top_info_1.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_top_info_1.setFont(font)
        self.label_top_info_1.setStyleSheet("color: rgb(98, 103, 111); ")
        self.label_top_info_1.setText("")
        self.label_top_info_1.setObjectName("label_top_info_1")
        self.horizontalLayout_8.addWidget(self.label_top_info_1)
        self.label_top_info_2 = QtWidgets.QLabel(self.frame_top_info)
        self.label_top_info_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_top_info_2.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_top_info_2.setFont(font)
        self.label_top_info_2.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_top_info_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_top_info_2.setObjectName("label_top_info_2")
        self.horizontalLayout_8.addWidget(self.label_top_info_2)
        self.verticalLayout_2.addWidget(self.frame_top_info)
        self.horizontalLayout_3.addWidget(self.frame_top_right)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_center.sizePolicy().hasHeightForWidth())
        self.frame_center.setSizePolicy(sizePolicy)
        self.frame_center.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_left_menu.setStyleSheet("background-color: rgb(32,34,67);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.layout_menus = QtWidgets.QVBoxLayout(self.frame_menus)
        self.layout_menus.setContentsMargins(0, 0, 0, 0)
        self.layout_menus.setSpacing(0)
        self.layout_menus.setObjectName("layout_menus")
        self.verticalLayout_5.addWidget(self.frame_menus, 0, QtCore.Qt.AlignTop)
        self.frame_extra_menus = QtWidgets.QFrame(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_extra_menus.sizePolicy().hasHeightForWidth())
        self.frame_extra_menus.setSizePolicy(sizePolicy)
        self.frame_extra_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.layout_menu_bottom = QtWidgets.QVBoxLayout(self.frame_extra_menus)
        self.layout_menu_bottom.setContentsMargins(0, 0, 0, 25)
        self.layout_menu_bottom.setSpacing(10)
        self.layout_menu_bottom.setObjectName("layout_menu_bottom")
        self.label_user_icon = QtWidgets.QLabel(self.frame_extra_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_icon.sizePolicy().hasHeightForWidth())
        self.label_user_icon.setSizePolicy(sizePolicy)
        self.label_user_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.label_user_icon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_user_icon.setFont(font)
        self.label_user_icon.setStyleSheet("QLabel {\n"
"    border-radius: 30px;\n"
"    background-color: #4c5091;\n"
"    border: 5px solid #3a3e77;\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.label_user_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_icon.setObjectName("label_user_icon")
        self.layout_menu_bottom.addWidget(self.label_user_icon, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_extra_menus, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_content_right = QtWidgets.QFrame(self.frame_center)
        self.frame_content_right.setStyleSheet("")
        self.frame_content_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_content_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_content = QtWidgets.QFrame(self.frame_content_right)
        self.frame_content.setStyleSheet("#frame_content{\n"
"background: qlineargradient( x1:0.5 y1:1, x2:0.5 y2:0.2, stop:0 #4b4e8e, stop:1 #686bbf);}\n"
"\n"
"")
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.page_home)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.page_home)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.page_home)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.stackedWidget.addWidget(self.page_home)
        self.page_appointments = QtWidgets.QWidget()
        self.page_appointments.setObjectName("page_appointments")
        self.verticalLayout_page_appointments = QtWidgets.QVBoxLayout(self.page_appointments)
        self.verticalLayout_page_appointments.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_page_appointments.setSpacing(0)
        self.verticalLayout_page_appointments.setObjectName("verticalLayout_page_appointments")
        self.tabWidget_faculty_appnt = QtWidgets.QTabWidget(self.page_appointments)
        self.tabWidget_faculty_appnt.setStyleSheet("\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"border:0\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"left: 15px; /* move to the right by 12px */\n"
"}\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that it reads QTabBar _not_ QTabWidget */\n"
"\n"
"QTabBar{\n"
"font-size: 12pt;\n"
"font-family: Helvetica;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"color: white;\n"
"background-color: transparent;\n"
"margin-left: 7px;\n"
"margin-right: 7px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"background-color: #7a7ecb;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"border-top: 0;\n"
"border-left: 0;\n"
"border-right: 0;\n"
"border-bottom: 3px solid #69cdff;\n"
"}")
        self.tabWidget_faculty_appnt.setObjectName("tabWidget_faculty_appnt")
        self.fac_appnt_main = QtWidgets.QWidget()
        self.fac_appnt_main.setObjectName("fac_appnt_main")
        self.verticalLayout_fac_appnt_main = QtWidgets.QVBoxLayout(self.fac_appnt_main)
        self.verticalLayout_fac_appnt_main.setContentsMargins(12, 8, 12, 12)
        self.verticalLayout_fac_appnt_main.setSpacing(0)
        self.verticalLayout_fac_appnt_main.setObjectName("verticalLayout_fac_appnt_main")
        self.fac_appnt_main_Fcontent = QtWidgets.QFrame(self.fac_appnt_main)
        self.fac_appnt_main_Fcontent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_appnt_main_Fcontent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_appnt_main_Fcontent.setObjectName("fac_appnt_main_Fcontent")
        self.horizontalLayout_fac_appnt_main_Fcontent = QtWidgets.QHBoxLayout(self.fac_appnt_main_Fcontent)
        self.horizontalLayout_fac_appnt_main_Fcontent.setContentsMargins(10, 8, 10, 10)
        self.horizontalLayout_fac_appnt_main_Fcontent.setSpacing(18)
        self.horizontalLayout_fac_appnt_main_Fcontent.setObjectName("horizontalLayout_fac_appnt_main_Fcontent")
        self.fac_appnt_main_FcontentLeft = QtWidgets.QFrame(self.fac_appnt_main_Fcontent)
        self.fac_appnt_main_FcontentLeft.setStyleSheet("QWidget{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.fac_appnt_main_FcontentLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_appnt_main_FcontentLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_appnt_main_FcontentLeft.setObjectName("fac_appnt_main_FcontentLeft")
        self.verticalLayout_fac_appnt_main_FcontentLeft = QtWidgets.QVBoxLayout(self.fac_appnt_main_FcontentLeft)
        self.verticalLayout_fac_appnt_main_FcontentLeft.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fac_appnt_main_FcontentLeft.setSpacing(20)
        self.verticalLayout_fac_appnt_main_FcontentLeft.setObjectName("verticalLayout_fac_appnt_main_FcontentLeft")
        self.fac_FcontentLeft_top = QtWidgets.QFrame(self.fac_appnt_main_FcontentLeft)
        self.fac_FcontentLeft_top.setStyleSheet("")
        self.fac_FcontentLeft_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_FcontentLeft_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_FcontentLeft_top.setObjectName("fac_FcontentLeft_top")
        self.verticalLayout_fac_FcontentLeft_top = QtWidgets.QVBoxLayout(self.fac_FcontentLeft_top)
        self.verticalLayout_fac_FcontentLeft_top.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fac_FcontentLeft_top.setObjectName("verticalLayout_fac_FcontentLeft_top")
        self.fac_Favl_top = QtWidgets.QFrame(self.fac_FcontentLeft_top)
        self.fac_Favl_top.setStyleSheet("QFrame{\n"
"border:0;\n"
"}")
        self.fac_Favl_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_Favl_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_Favl_top.setObjectName("fac_Favl_top")
        self.horizontalLayout_fac_Favl_top = QtWidgets.QHBoxLayout(self.fac_Favl_top)
        self.horizontalLayout_fac_Favl_top.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_fac_Favl_top.setSpacing(0)
        self.horizontalLayout_fac_Favl_top.setObjectName("horizontalLayout_fac_Favl_top")
        self.fac_avl_label = QtWidgets.QLabel(self.fac_Favl_top)
        self.fac_avl_label.setStyleSheet("QWidget{\n"
"border:0;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family: Arial;\n"
"font-size: 12pt;\n"
"margin-left: 4px;\n"
"}")
        self.fac_avl_label.setObjectName("fac_avl_label")
        self.horizontalLayout_fac_Favl_top.addWidget(self.fac_avl_label)
        self.fac_avl_addsched = QtWidgets.QFrame(self.fac_Favl_top)
        self.fac_avl_addsched.setStyleSheet("QPushButton:hover {\n"
"    background-color: #7a7ecb;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.fac_avl_addsched.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_avl_addsched.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_avl_addsched.setObjectName("fac_avl_addsched")
        self.horizontalLayout_fac_avl_addsched = QtWidgets.QHBoxLayout(self.fac_avl_addsched)
        self.horizontalLayout_fac_avl_addsched.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_fac_avl_addsched.setSpacing(4)
        self.horizontalLayout_fac_avl_addsched.setObjectName("horizontalLayout_fac_avl_addsched")
        self.clear = QtWidgets.QPushButton(self.fac_avl_addsched)
        self.clear.setStyleSheet("")
        self.clear.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/20x20/icons/20x20/cil-trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.clear.setIcon(icon3)
        self.clear.setIconSize(QtCore.QSize(24, 24))
        self.clear.setObjectName("clear")
        self.horizontalLayout_fac_avl_addsched.addWidget(self.clear)
        self.horizontalLayout_fac_Favl_top.addWidget(self.fac_avl_addsched, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_fac_Favl_top.setStretch(0, 1)
        self.horizontalLayout_fac_Favl_top.setStretch(1, 4)
        self.verticalLayout_fac_FcontentLeft_top.addWidget(self.fac_Favl_top)
        self.fac_avl_contentF = QtWidgets.QFrame(self.fac_FcontentLeft_top)
        self.fac_avl_contentF.setStyleSheet("QWidget{\n"
"border: 1px solid #69cdff;\n"
"color: black;\n"
"background-color: rgb(248, 248, 248);\n"
"}\n"
"\n"
"#fac_avl_contentF QFrame{\n"
"border:0;\n"
"}")
        self.fac_avl_contentF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_avl_contentF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_avl_contentF.setObjectName("fac_avl_contentF")
        self.verticalLayout_fac_avl_contentF = QtWidgets.QVBoxLayout(self.fac_avl_contentF)
        self.verticalLayout_fac_avl_contentF.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fac_avl_contentF.setSpacing(0)
        self.verticalLayout_fac_avl_contentF.setObjectName("verticalLayout_fac_avl_contentF")
        self.fac_avl_contents = QtWidgets.QFrame(self.fac_avl_contentF)
        self.fac_avl_contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_avl_contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_avl_contents.setObjectName("fac_avl_contents")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.fac_avl_contents)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.day_avlF = QtWidgets.QFrame(self.fac_avl_contents)
        self.day_avlF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.day_avlF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.day_avlF.setObjectName("day_avlF")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.day_avlF)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.day_avl_l1 = QtWidgets.QLabel(self.day_avlF)
        self.day_avl_l1.setStyleSheet("font-size:10pt;")
        self.day_avl_l1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.day_avl_l1.setObjectName("day_avl_l1")
        self.verticalLayout_12.addWidget(self.day_avl_l1)
        self.day_avl_l2 = QtWidgets.QLabel(self.day_avlF)
        self.day_avl_l2.setStyleSheet("font-size:9pt;\n"
"margin-top:4px;")
        self.day_avl_l2.setText("")
        self.day_avl_l2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.day_avl_l2.setObjectName("day_avl_l2")
        self.verticalLayout_12.addWidget(self.day_avl_l2)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 10)
        self.horizontalLayout_13.addWidget(self.day_avlF)
        self.time_avlF = QtWidgets.QFrame(self.fac_avl_contents)
        self.time_avlF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_avlF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_avlF.setObjectName("time_avlF")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.time_avlF)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.time_avl_l1 = QtWidgets.QLabel(self.time_avlF)
        self.time_avl_l1.setStyleSheet("font-size:10pt;")
        self.time_avl_l1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.time_avl_l1.setObjectName("time_avl_l1")
        self.verticalLayout_13.addWidget(self.time_avl_l1)
        self.time_avl_l2 = QtWidgets.QLabel(self.time_avlF)
        self.time_avl_l2.setStyleSheet("font-size:9pt;\n"
"margin-top:4px;")
        self.time_avl_l2.setText("")
        self.time_avl_l2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.time_avl_l2.setObjectName("time_avl_l2")
        self.verticalLayout_13.addWidget(self.time_avl_l2)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 10)
        self.horizontalLayout_13.addWidget(self.time_avlF)
        self.verticalLayout_fac_avl_contentF.addWidget(self.fac_avl_contents)
        self.fac_avl_ctrl = QtWidgets.QFrame(self.fac_avl_contentF)
        self.fac_avl_ctrl.setStyleSheet("/* COMBOBOX */\n"
"QComboBox{\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: #7a7ecb;\n"
"}")
        self.fac_avl_ctrl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_avl_ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_avl_ctrl.setObjectName("fac_avl_ctrl")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.fac_avl_ctrl)
        self.horizontalLayout_14.setContentsMargins(10, 8, 10, 8)
        self.horizontalLayout_14.setSpacing(18)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.comboBox_day_avl = QtWidgets.QComboBox(self.fac_avl_ctrl)
        self.comboBox_day_avl.setObjectName("comboBox_day_avl")
        self.horizontalLayout_14.addWidget(self.comboBox_day_avl)
        self.comboBox_time_avl = QtWidgets.QComboBox(self.fac_avl_ctrl)
        self.comboBox_time_avl.setObjectName("comboBox_time_avl")
        self.horizontalLayout_14.addWidget(self.comboBox_time_avl)
        self.comboBox_colorTheme = QtWidgets.QComboBox(self.fac_avl_ctrl)
        self.comboBox_colorTheme.setObjectName("comboBox_colorTheme")
        self.horizontalLayout_14.addWidget(self.comboBox_colorTheme)
        self.verticalLayout_fac_avl_contentF.addWidget(self.fac_avl_ctrl)
        self.verticalLayout_fac_avl_contentF.setStretch(0, 5)
        self.verticalLayout_fac_avl_contentF.setStretch(1, 1)
        self.verticalLayout_fac_FcontentLeft_top.addWidget(self.fac_avl_contentF)
        self.verticalLayout_fac_FcontentLeft_top.setStretch(0, 1)
        self.verticalLayout_fac_FcontentLeft_top.setStretch(1, 20)
        self.verticalLayout_fac_appnt_main_FcontentLeft.addWidget(self.fac_FcontentLeft_top)
        self.fac_FcontentLeft_bot = QtWidgets.QFrame(self.fac_appnt_main_FcontentLeft)
        self.fac_FcontentLeft_bot.setStyleSheet("QWidget{\n"
"border: 1px solid #69cdff;\n"
"color: black;\n"
"background-color: rgb(248, 248, 248);\n"
"}")
        self.fac_FcontentLeft_bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_FcontentLeft_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_FcontentLeft_bot.setObjectName("fac_FcontentLeft_bot")
        self.verticalLayout_fac_FcontentLeft_bot = QtWidgets.QVBoxLayout(self.fac_FcontentLeft_bot)
        self.verticalLayout_fac_FcontentLeft_bot.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_fac_FcontentLeft_bot.setSpacing(0)
        self.verticalLayout_fac_FcontentLeft_bot.setObjectName("verticalLayout_fac_FcontentLeft_bot")
        self.queue_label = QtWidgets.QLabel(self.fac_FcontentLeft_bot)
        self.queue_label.setStyleSheet("QLabel{\n"
"border: 0;\n"
"}")
        self.queue_label.setObjectName("queue_label")
        self.verticalLayout_fac_FcontentLeft_bot.addWidget(self.queue_label)
        self.verticalLayout_fac_appnt_main_FcontentLeft.addWidget(self.fac_FcontentLeft_bot)
        self.verticalLayout_fac_appnt_main_FcontentLeft.setStretch(0, 5)
        self.verticalLayout_fac_appnt_main_FcontentLeft.setStretch(1, 4)
        self.horizontalLayout_fac_appnt_main_Fcontent.addWidget(self.fac_appnt_main_FcontentLeft)
        self.fac_appnt_main_FcontentRight = QtWidgets.QFrame(self.fac_appnt_main_Fcontent)
        self.fac_appnt_main_FcontentRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_appnt_main_FcontentRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_appnt_main_FcontentRight.setObjectName("fac_appnt_main_FcontentRight")
        self.verticalLayout_fac_appnt_main_FcontentRight = QtWidgets.QVBoxLayout(self.fac_appnt_main_FcontentRight)
        self.verticalLayout_fac_appnt_main_FcontentRight.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fac_appnt_main_FcontentRight.setSpacing(20)
        self.verticalLayout_fac_appnt_main_FcontentRight.setObjectName("verticalLayout_fac_appnt_main_FcontentRight")
        self.fac_FcontentRight_top = QtWidgets.QFrame(self.fac_appnt_main_FcontentRight)
        self.fac_FcontentRight_top.setStyleSheet("QWidget{\n"
"border: 1px solid #69cdff;\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.fac_FcontentRight_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_FcontentRight_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_FcontentRight_top.setObjectName("fac_FcontentRight_top")
        self.verticalLayout_fac_FcontentRight_top = QtWidgets.QVBoxLayout(self.fac_FcontentRight_top)
        self.verticalLayout_fac_FcontentRight_top.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_fac_FcontentRight_top.setSpacing(0)
        self.verticalLayout_fac_FcontentRight_top.setObjectName("verticalLayout_fac_FcontentRight_top")
        self.fac_calendarWidget_appnts = QtWidgets.QCalendarWidget(self.fac_FcontentRight_top)
        self.fac_calendarWidget_appnts.setStyleSheet("QWidget{background-color: rgb(248, 248, 248);}\n"
"\n"
"\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    height: 40px;\n"
"    width: 75px;\n"
"    color: black;\n"
"    font-size: 12pt;\n"
"    icon-size: 30px, 30px;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    width: 135px;\n"
"    left: 3px;\n"
"    color: black;\n"
"    font-size: 12pt;\n"
"    background-color: rgb(219, 219, 219);\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox { \n"
"    width: 80px; \n"
"    font-size:12pt; \n"
"    color: black; \n"
"    background-color: transparent; \n"
"    selection-background-color: rgb(219, 219, 219);\n"
"    selection-color: black;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox::up-button { \n"
"subcontrol-origin: border;  \n"
"subcontrol-position: top right;  \n"
"width:25px; \n"
"}\n"
"\n"
"QCalendarWidget QSpinBox::down-button {\n"
"subcontrol-origin: border; \n"
"subcontrol-position: bottom right;  \n"
"width:25px;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox::up-arrow { width:20px;  height:20px; }\n"
"\n"
"QCalendarWidget QSpinBox::down-arrow { width:20px;  height:20px; }\n"
"\n"
"/* header row */\n"
"QCalendarWidget QWidget { alternate-background-color: transparent; border:0;}\n"
"\n"
"/* normal days */\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    font-size:12pt;  \n"
"    color: black;  \n"
"    selection-background-color: rgba(242, 242, 242, 40); \n"
"    selection-color: rgb(0, 255, 0); \n"
"}\n"
"\n"
"/* days in other months */\n"
"QCalendarWidget QAbstractItemView:disabled {color: rgb(148, 148, 148); }")
        self.fac_calendarWidget_appnts.setObjectName("fac_calendarWidget_appnts")
        self.verticalLayout_fac_FcontentRight_top.addWidget(self.fac_calendarWidget_appnts)
        self.verticalLayout_fac_appnt_main_FcontentRight.addWidget(self.fac_FcontentRight_top)
        self.fac_FcontentRight_bot = QtWidgets.QFrame(self.fac_appnt_main_FcontentRight)
        self.fac_FcontentRight_bot.setStyleSheet("")
        self.fac_FcontentRight_bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_FcontentRight_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_FcontentRight_bot.setObjectName("fac_FcontentRight_bot")
        self.verticalLayout_fac_FcontentRight_bot = QtWidgets.QVBoxLayout(self.fac_FcontentRight_bot)
        self.verticalLayout_fac_FcontentRight_bot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fac_FcontentRight_bot.setObjectName("verticalLayout_fac_FcontentRight_bot")
        self.fac_FcontentRight_bot_Ltop = QtWidgets.QLabel(self.fac_FcontentRight_bot)
        self.fac_FcontentRight_bot_Ltop.setStyleSheet("font-size: 12pt;\n"
"color: rgb(255, 255, 255);\n"
"border: 0;\n"
"margin-left: 4px;")
        self.fac_FcontentRight_bot_Ltop.setObjectName("fac_FcontentRight_bot_Ltop")
        self.verticalLayout_fac_FcontentRight_bot.addWidget(self.fac_FcontentRight_bot_Ltop)
        self.fac_scrollArea_logs = QtWidgets.QScrollArea(self.fac_FcontentRight_bot)
        self.fac_scrollArea_logs.setStyleSheet("QScrollArea{\n"
"border: 1px solid #69cdff;\n"
"}\n"
"\n"
"QWidget{background-color: rgb(248, 248, 248);}\n"
"")
        self.fac_scrollArea_logs.setWidgetResizable(True)
        self.fac_scrollArea_logs.setObjectName("fac_scrollArea_logs")
        self.fac_scrollArea_logs_contents = QtWidgets.QWidget()
        self.fac_scrollArea_logs_contents.setGeometry(QtCore.QRect(0, 0, 458, 105))
        self.fac_scrollArea_logs_contents.setObjectName("fac_scrollArea_logs_contents")
        self.horizontalLayout_fac_scrollArea_logs_contents = QtWidgets.QHBoxLayout(self.fac_scrollArea_logs_contents)
        self.horizontalLayout_fac_scrollArea_logs_contents.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_fac_scrollArea_logs_contents.setObjectName("horizontalLayout_fac_scrollArea_logs_contents")
        self.fac_scrollArea_logs.setWidget(self.fac_scrollArea_logs_contents)
        self.verticalLayout_fac_FcontentRight_bot.addWidget(self.fac_scrollArea_logs)
        self.verticalLayout_fac_FcontentRight_bot.setStretch(0, 1)
        self.verticalLayout_fac_FcontentRight_bot.setStretch(1, 20)
        self.verticalLayout_fac_appnt_main_FcontentRight.addWidget(self.fac_FcontentRight_bot)
        self.verticalLayout_fac_appnt_main_FcontentRight.setStretch(0, 6)
        self.verticalLayout_fac_appnt_main_FcontentRight.setStretch(1, 2)
        self.horizontalLayout_fac_appnt_main_Fcontent.addWidget(self.fac_appnt_main_FcontentRight)
        self.horizontalLayout_fac_appnt_main_Fcontent.setStretch(0, 4)
        self.horizontalLayout_fac_appnt_main_Fcontent.setStretch(1, 5)
        self.verticalLayout_fac_appnt_main.addWidget(self.fac_appnt_main_Fcontent)
        self.tabWidget_faculty_appnt.addTab(self.fac_appnt_main, "")
        self.fac_appnt_avl = QtWidgets.QWidget()
        self.fac_appnt_avl.setObjectName("fac_appnt_avl")
        self.verticalLayout_fac_appnt_avl = QtWidgets.QVBoxLayout(self.fac_appnt_avl)
        self.verticalLayout_fac_appnt_avl.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fac_appnt_avl.setSpacing(0)
        self.verticalLayout_fac_appnt_avl.setObjectName("verticalLayout_fac_appnt_avl")
        self.tabWidget_faculty_appnt.addTab(self.fac_appnt_avl, "")
        self.fac_appnt_histofappnts = QtWidgets.QWidget()
        self.fac_appnt_histofappnts.setStyleSheet("")
        self.fac_appnt_histofappnts.setObjectName("fac_appnt_histofappnts")
        self.verticalLayout_fac_appnt_histofappnts = QtWidgets.QVBoxLayout(self.fac_appnt_histofappnts)
        self.verticalLayout_fac_appnt_histofappnts.setContentsMargins(20, 8, 20, 20)
        self.verticalLayout_fac_appnt_histofappnts.setObjectName("verticalLayout_fac_appnt_histofappnts")
        self.fac_appnt_Fhistofappnts_Ftop = QtWidgets.QFrame(self.fac_appnt_histofappnts)
        self.fac_appnt_Fhistofappnts_Ftop.setStyleSheet("color: rgb(255, 255, 255);")
        self.fac_appnt_Fhistofappnts_Ftop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_appnt_Fhistofappnts_Ftop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_appnt_Fhistofappnts_Ftop.setObjectName("fac_appnt_Fhistofappnts_Ftop")
        self.horizontalLayout_fac_appnt_Fhistofappnts_Ftop = QtWidgets.QHBoxLayout(self.fac_appnt_Fhistofappnts_Ftop)
        self.horizontalLayout_fac_appnt_Fhistofappnts_Ftop.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_fac_appnt_Fhistofappnts_Ftop.setObjectName("horizontalLayout_fac_appnt_Fhistofappnts_Ftop")
        self.fac_Fhistofappnts_Ltop = QtWidgets.QLabel(self.fac_appnt_Fhistofappnts_Ftop)
        self.fac_Fhistofappnts_Ltop.setStyleSheet("QWidget{\n"
"margin-left: 4px;\n"
"font-size: 12pt;\n"
"}")
        self.fac_Fhistofappnts_Ltop.setIndent(-1)
        self.fac_Fhistofappnts_Ltop.setObjectName("fac_Fhistofappnts_Ltop")
        self.horizontalLayout_fac_appnt_Fhistofappnts_Ftop.addWidget(self.fac_Fhistofappnts_Ltop)
        self.fac_appnt_histofappnts_Ftop_Fright = QtWidgets.QFrame(self.fac_appnt_Fhistofappnts_Ftop)
        self.fac_appnt_histofappnts_Ftop_Fright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fac_appnt_histofappnts_Ftop_Fright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fac_appnt_histofappnts_Ftop_Fright.setObjectName("fac_appnt_histofappnts_Ftop_Fright")
        self.horizontalLayout_fac_appnt_Fhistofappnts_Ftop.addWidget(self.fac_appnt_histofappnts_Ftop_Fright)
        self.verticalLayout_fac_appnt_histofappnts.addWidget(self.fac_appnt_Fhistofappnts_Ftop)
        self.fac_scrollarea_histofappnts = QtWidgets.QScrollArea(self.fac_appnt_histofappnts)
        self.fac_scrollarea_histofappnts.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.fac_scrollarea_histofappnts.setWidgetResizable(True)
        self.fac_scrollarea_histofappnts.setObjectName("fac_scrollarea_histofappnts")
        self.fac_scrollAreaWidgetContents_histofappnts = QtWidgets.QWidget()
        self.fac_scrollAreaWidgetContents_histofappnts.setGeometry(QtCore.QRect(0, 0, 858, 514))
        self.fac_scrollAreaWidgetContents_histofappnts.setObjectName("fac_scrollAreaWidgetContents_histofappnts")
        self.verticalLayout_fac_scrollAreaWidgetContents_histofappnts = QtWidgets.QVBoxLayout(self.fac_scrollAreaWidgetContents_histofappnts)
        self.verticalLayout_fac_scrollAreaWidgetContents_histofappnts.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_fac_scrollAreaWidgetContents_histofappnts.setSpacing(0)
        self.verticalLayout_fac_scrollAreaWidgetContents_histofappnts.setObjectName("verticalLayout_fac_scrollAreaWidgetContents_histofappnts")
        self.fac_tableView_histofappnts = QtWidgets.QTableView(self.fac_scrollAreaWidgetContents_histofappnts)
        self.fac_tableView_histofappnts.setObjectName("fac_tableView_histofappnts")
        self.verticalLayout_fac_scrollAreaWidgetContents_histofappnts.addWidget(self.fac_tableView_histofappnts)
        self.fac_scrollarea_histofappnts.setWidget(self.fac_scrollAreaWidgetContents_histofappnts)
        self.verticalLayout_fac_appnt_histofappnts.addWidget(self.fac_scrollarea_histofappnts)
        self.verticalLayout_fac_appnt_histofappnts.setStretch(0, 1)
        self.verticalLayout_fac_appnt_histofappnts.setStretch(1, 20)
        self.tabWidget_faculty_appnt.addTab(self.fac_appnt_histofappnts, "")
        self.verticalLayout_page_appointments.addWidget(self.tabWidget_faculty_appnt)
        self.stackedWidget.addWidget(self.page_appointments)
        self.page_special_services = QtWidgets.QWidget()
        self.page_special_services.setObjectName("page_special_services")
        self.verticalLayout_page_special_services = QtWidgets.QVBoxLayout(self.page_special_services)
        self.verticalLayout_page_special_services.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_page_special_services.setSpacing(0)
        self.verticalLayout_page_special_services.setObjectName("verticalLayout_page_special_services")
        self.tabWidget_faculty_ss = QtWidgets.QTabWidget(self.page_special_services)
        self.tabWidget_faculty_ss.setStyleSheet("\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"border:0\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"left: 15px; /* move to the right by 12px */\n"
"}\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that it reads QTabBar _not_ QTabWidget */\n"
"\n"
"QTabBar{\n"
"font-size: 12pt;\n"
"font-family: Helvetica;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"color: white;\n"
"background-color: transparent;\n"
"margin-left: 7px;\n"
"margin-right: 7px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"background-color: gray;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"border-top: 0;\n"
"border-left: 0;\n"
"border-right: 0;\n"
"border-bottom: 3px solid #69cdff;\n"
"}")
        self.tabWidget_faculty_ss.setObjectName("tabWidget_faculty_ss")
        self.faculty_ss_mainTab = QtWidgets.QWidget()
        self.faculty_ss_mainTab.setObjectName("faculty_ss_mainTab")
        self.verticalLayout_faculty_ss_mainTab = QtWidgets.QVBoxLayout(self.faculty_ss_mainTab)
        self.verticalLayout_faculty_ss_mainTab.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_ss_mainTab.setSpacing(0)
        self.verticalLayout_faculty_ss_mainTab.setObjectName("verticalLayout_faculty_ss_mainTab")
        self.page_faculty_Fss = QtWidgets.QFrame(self.faculty_ss_mainTab)
        self.page_faculty_Fss.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_Fss.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_Fss.setObjectName("page_faculty_Fss")
        self.horizontalLayout_page_faculty_Fss = QtWidgets.QHBoxLayout(self.page_faculty_Fss)
        self.horizontalLayout_page_faculty_Fss.setContentsMargins(16, 10, 16, 16)
        self.horizontalLayout_page_faculty_Fss.setSpacing(22)
        self.horizontalLayout_page_faculty_Fss.setObjectName("horizontalLayout_page_faculty_Fss")
        self.page_faculty_ss_Fleft = QtWidgets.QFrame(self.page_faculty_Fss)
        self.page_faculty_ss_Fleft.setStyleSheet("QFrame{\n"
"border: 0;\n"
"}\n"
"\n"
"QScrollArea{border: 1px solid #69cdff;}")
        self.page_faculty_ss_Fleft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_ss_Fleft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_ss_Fleft.setObjectName("page_faculty_ss_Fleft")
        self.verticalLayout_page_faculty_ss_Fleft = QtWidgets.QVBoxLayout(self.page_faculty_ss_Fleft)
        self.verticalLayout_page_faculty_ss_Fleft.setObjectName("verticalLayout_page_faculty_ss_Fleft")
        self.faculty_ss_Fleft_tcreatedLabel = QtWidgets.QLabel(self.page_faculty_ss_Fleft)
        self.faculty_ss_Fleft_tcreatedLabel.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-size: 12pt;\n"
"margin-left: 4px;\n"
"border:0 ;\n"
"}")
        self.faculty_ss_Fleft_tcreatedLabel.setObjectName("faculty_ss_Fleft_tcreatedLabel")
        self.verticalLayout_page_faculty_ss_Fleft.addWidget(self.faculty_ss_Fleft_tcreatedLabel)
        self.faculty_scrollArea_tcreated = QtWidgets.QScrollArea(self.page_faculty_ss_Fleft)
        self.faculty_scrollArea_tcreated.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"")
        self.faculty_scrollArea_tcreated.setWidgetResizable(True)
        self.faculty_scrollArea_tcreated.setObjectName("faculty_scrollArea_tcreated")
        self.faculty_scrollArea_tcreated_contents = QtWidgets.QWidget()
        self.faculty_scrollArea_tcreated_contents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.faculty_scrollArea_tcreated_contents.setObjectName("faculty_scrollArea_tcreated_contents")
        self.verticalLayout_faculty_scrollArea_tcreated_contents = QtWidgets.QVBoxLayout(self.faculty_scrollArea_tcreated_contents)
        self.verticalLayout_faculty_scrollArea_tcreated_contents.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_faculty_scrollArea_tcreated_contents.setSpacing(4)
        self.verticalLayout_faculty_scrollArea_tcreated_contents.setObjectName("verticalLayout_faculty_scrollArea_tcreated_contents")
        self.faculty_scrollArea_tcreated.setWidget(self.faculty_scrollArea_tcreated_contents)
        self.verticalLayout_page_faculty_ss_Fleft.addWidget(self.faculty_scrollArea_tcreated)
        self.verticalLayout_page_faculty_ss_Fleft.setStretch(0, 1)
        self.verticalLayout_page_faculty_ss_Fleft.setStretch(1, 20)
        self.horizontalLayout_page_faculty_Fss.addWidget(self.page_faculty_ss_Fleft)
        self.page_faculty_ss_Fright = QtWidgets.QFrame(self.page_faculty_Fss)
        self.page_faculty_ss_Fright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_ss_Fright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_ss_Fright.setObjectName("page_faculty_ss_Fright")
        self.verticalLayout_page_faculty_ss_Fright = QtWidgets.QVBoxLayout(self.page_faculty_ss_Fright)
        self.verticalLayout_page_faculty_ss_Fright.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_page_faculty_ss_Fright.setSpacing(22)
        self.verticalLayout_page_faculty_ss_Fright.setObjectName("verticalLayout_page_faculty_ss_Fright")
        self.page_faculty_ss_right_Ftop = QtWidgets.QFrame(self.page_faculty_ss_Fright)
        self.page_faculty_ss_right_Ftop.setStyleSheet("QFrame{\n"
"border: 0;\n"
"}")
        self.page_faculty_ss_right_Ftop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_ss_right_Ftop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_ss_right_Ftop.setObjectName("page_faculty_ss_right_Ftop")
        self.verticalLayout_page_faculty_ss_right_Ftop = QtWidgets.QVBoxLayout(self.page_faculty_ss_right_Ftop)
        self.verticalLayout_page_faculty_ss_right_Ftop.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_page_faculty_ss_right_Ftop.setObjectName("verticalLayout_page_faculty_ss_right_Ftop")
        self.faculty_ss_right_Ftop_iconLabel = QtWidgets.QLabel(self.page_faculty_ss_right_Ftop)
        self.faculty_ss_right_Ftop_iconLabel.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-size: 12pt;\n"
"margin-left: 4px;\n"
"border:0 ;\n"
"}")
        self.faculty_ss_right_Ftop_iconLabel.setObjectName("faculty_ss_right_Ftop_iconLabel")
        self.verticalLayout_page_faculty_ss_right_Ftop.addWidget(self.faculty_ss_right_Ftop_iconLabel)
        self.page_faculty_ss_right_Ftop_iconContents = QtWidgets.QFrame(self.page_faculty_ss_right_Ftop)
        self.page_faculty_ss_right_Ftop_iconContents.setStyleSheet("QFrame{\n"
"border: 1px solid #69cdff;\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.page_faculty_ss_right_Ftop_iconContents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_ss_right_Ftop_iconContents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_ss_right_Ftop_iconContents.setObjectName("page_faculty_ss_right_Ftop_iconContents")
        self.gridLayout_page_faculty_ss_right_Ftop_iconContents = QtWidgets.QGridLayout(self.page_faculty_ss_right_Ftop_iconContents)
        self.gridLayout_page_faculty_ss_right_Ftop_iconContents.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_page_faculty_ss_right_Ftop_iconContents.setSpacing(3)
        self.gridLayout_page_faculty_ss_right_Ftop_iconContents.setObjectName("gridLayout_page_faculty_ss_right_Ftop_iconContents")
        self.verticalLayout_page_faculty_ss_right_Ftop.addWidget(self.page_faculty_ss_right_Ftop_iconContents)
        self.verticalLayout_page_faculty_ss_right_Ftop.setStretch(0, 1)
        self.verticalLayout_page_faculty_ss_right_Ftop.setStretch(1, 10)
        self.verticalLayout_page_faculty_ss_Fright.addWidget(self.page_faculty_ss_right_Ftop)
        self.page_faculty_ss_right_Fbot = QtWidgets.QFrame(self.page_faculty_ss_Fright)
        self.page_faculty_ss_right_Fbot.setStyleSheet("QFrame{\n"
"border: 0;\n"
"}\n"
"\n"
"QScrollArea{border: 1px solid #69cdff;}")
        self.page_faculty_ss_right_Fbot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_ss_right_Fbot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_ss_right_Fbot.setObjectName("page_faculty_ss_right_Fbot")
        self.verticalLayout_page_faculty_ss_right_Fbot = QtWidgets.QVBoxLayout(self.page_faculty_ss_right_Fbot)
        self.verticalLayout_page_faculty_ss_right_Fbot.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_page_faculty_ss_right_Fbot.setSpacing(4)
        self.verticalLayout_page_faculty_ss_right_Fbot.setObjectName("verticalLayout_page_faculty_ss_right_Fbot")
        self.faculty_ss_right_bot_Ftcreation = QtWidgets.QFrame(self.page_faculty_ss_right_Fbot)
        self.faculty_ss_right_bot_Ftcreation.setStyleSheet("QFrame{\n"
"border: 0;\n"
"}")
        self.faculty_ss_right_bot_Ftcreation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_ss_right_bot_Ftcreation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_ss_right_bot_Ftcreation.setObjectName("faculty_ss_right_bot_Ftcreation")
        self.horizontalLayout_faculty_ss_right_bot_Ftcreation = QtWidgets.QHBoxLayout(self.faculty_ss_right_bot_Ftcreation)
        self.horizontalLayout_faculty_ss_right_bot_Ftcreation.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_faculty_ss_right_bot_Ftcreation.setSpacing(0)
        self.horizontalLayout_faculty_ss_right_bot_Ftcreation.setObjectName("horizontalLayout_faculty_ss_right_bot_Ftcreation")
        self.faculty_ss_tcreationLabel = QtWidgets.QLabel(self.faculty_ss_right_bot_Ftcreation)
        self.faculty_ss_tcreationLabel.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-size: 12pt;\n"
"margin-left: 4px;\n"
"border:0 ;\n"
"}")
        self.faculty_ss_tcreationLabel.setObjectName("faculty_ss_tcreationLabel")
        self.horizontalLayout_faculty_ss_right_bot_Ftcreation.addWidget(self.faculty_ss_tcreationLabel)
        self.faculty_ss_right_bot_tcreation_Fright = QtWidgets.QFrame(self.faculty_ss_right_bot_Ftcreation)
        self.faculty_ss_right_bot_tcreation_Fright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_ss_right_bot_tcreation_Fright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_ss_right_bot_tcreation_Fright.setObjectName("faculty_ss_right_bot_tcreation_Fright")
        self.horizontalLayout_faculty_ss_right_bot_tcreation_Fright = QtWidgets.QHBoxLayout(self.faculty_ss_right_bot_tcreation_Fright)
        self.horizontalLayout_faculty_ss_right_bot_tcreation_Fright.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_faculty_ss_right_bot_tcreation_Fright.setSpacing(2)
        self.horizontalLayout_faculty_ss_right_bot_tcreation_Fright.setObjectName("horizontalLayout_faculty_ss_right_bot_tcreation_Fright")
        self.faculty_ss_right_top_tcreation_right_okCreationButton = QtWidgets.QPushButton(self.faculty_ss_right_bot_tcreation_Fright)
        self.faculty_ss_right_top_tcreation_right_okCreationButton.setStyleSheet("color: white;")
        self.faculty_ss_right_top_tcreation_right_okCreationButton.setObjectName("faculty_ss_right_top_tcreation_right_okCreationButton")
        self.horizontalLayout_faculty_ss_right_bot_tcreation_Fright.addWidget(self.faculty_ss_right_top_tcreation_right_okCreationButton)
        self.horizontalLayout_faculty_ss_right_bot_Ftcreation.addWidget(self.faculty_ss_right_bot_tcreation_Fright, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_page_faculty_ss_right_Fbot.addWidget(self.faculty_ss_right_bot_Ftcreation)
        self.faculty_scrollArea_tcreation = QtWidgets.QScrollArea(self.page_faculty_ss_right_Fbot)
        self.faculty_scrollArea_tcreation.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(248, 248, 248);")
        self.faculty_scrollArea_tcreation.setWidgetResizable(True)
        self.faculty_scrollArea_tcreation.setObjectName("faculty_scrollArea_tcreation")
        self.faculty_scrollArea_tcreation_contents = QtWidgets.QWidget()
        self.faculty_scrollArea_tcreation_contents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.faculty_scrollArea_tcreation_contents.setObjectName("faculty_scrollArea_tcreation_contents")
        self.verticalLayout_faculty_scrollArea_tcreation_contents = QtWidgets.QVBoxLayout(self.faculty_scrollArea_tcreation_contents)
        self.verticalLayout_faculty_scrollArea_tcreation_contents.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_faculty_scrollArea_tcreation_contents.setSpacing(0)
        self.verticalLayout_faculty_scrollArea_tcreation_contents.setObjectName("verticalLayout_faculty_scrollArea_tcreation_contents")
        self.faculty_scrollArea_tcreation.setWidget(self.faculty_scrollArea_tcreation_contents)
        self.verticalLayout_page_faculty_ss_right_Fbot.addWidget(self.faculty_scrollArea_tcreation)
        self.verticalLayout_page_faculty_ss_right_Fbot.setStretch(1, 10)
        self.verticalLayout_page_faculty_ss_Fright.addWidget(self.page_faculty_ss_right_Fbot)
        self.verticalLayout_page_faculty_ss_Fright.setStretch(0, 2)
        self.verticalLayout_page_faculty_ss_Fright.setStretch(1, 3)
        self.horizontalLayout_page_faculty_Fss.addWidget(self.page_faculty_ss_Fright)
        self.verticalLayout_faculty_ss_mainTab.addWidget(self.page_faculty_Fss)
        self.tabWidget_faculty_ss.addTab(self.faculty_ss_mainTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_faculty_ss.addTab(self.tab_2, "")
        self.verticalLayout_page_special_services.addWidget(self.tabWidget_faculty_ss)
        self.stackedWidget.addWidget(self.page_special_services)
        self.page_roomNkey = QtWidgets.QWidget()
        self.page_roomNkey.setObjectName("page_roomNkey")
        self.verticalLayout_page_roomNkey = QtWidgets.QVBoxLayout(self.page_roomNkey)
        self.verticalLayout_page_roomNkey.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_page_roomNkey.setSpacing(0)
        self.verticalLayout_page_roomNkey.setObjectName("verticalLayout_page_roomNkey")
        self.tabWidget_faculty_roomNkey = QtWidgets.QTabWidget(self.page_roomNkey)
        self.tabWidget_faculty_roomNkey.setStyleSheet("\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"border:0\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"left: 15px; /* move to the right by 12px */\n"
"}\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that it reads QTabBar _not_ QTabWidget */\n"
"\n"
"QTabBar{\n"
"font-size: 12pt;\n"
"font-family: Helvetica;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"color: white;\n"
"background-color: transparent;\n"
"margin-left: 7px;\n"
"margin-right: 7px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"background-color: gray;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"border-top: 0;\n"
"border-left: 0;\n"
"border-right: 0;\n"
"border-bottom: 3px solid #69cdff;\n"
"}")
        self.tabWidget_faculty_roomNkey.setObjectName("tabWidget_faculty_roomNkey")
        self.faculty_roomNkey_mainTab = QtWidgets.QWidget()
        self.faculty_roomNkey_mainTab.setObjectName("faculty_roomNkey_mainTab")
        self.verticalLayout_faculty_roomNkey_mainTab = QtWidgets.QVBoxLayout(self.faculty_roomNkey_mainTab)
        self.verticalLayout_faculty_roomNkey_mainTab.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_roomNkey_mainTab.setSpacing(0)
        self.verticalLayout_faculty_roomNkey_mainTab.setObjectName("verticalLayout_faculty_roomNkey_mainTab")
        self.page_faculty_FroomNkey = QtWidgets.QFrame(self.faculty_roomNkey_mainTab)
        self.page_faculty_FroomNkey.setStyleSheet("QFrame{\n"
"border: 0;\n"
"}")
        self.page_faculty_FroomNkey.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_FroomNkey.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_FroomNkey.setObjectName("page_faculty_FroomNkey")
        self.verticalLayout_page_faculty_FroomNkey = QtWidgets.QVBoxLayout(self.page_faculty_FroomNkey)
        self.verticalLayout_page_faculty_FroomNkey.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_page_faculty_FroomNkey.setSpacing(0)
        self.verticalLayout_page_faculty_FroomNkey.setObjectName("verticalLayout_page_faculty_FroomNkey")
        self.page_faculty_FroomNkey_contents = QtWidgets.QFrame(self.page_faculty_FroomNkey)
        self.page_faculty_FroomNkey_contents.setStyleSheet("QFrame{\n"
"border: 0;\n"
"}\n"
"\n"
"QLabel{\n"
"font: 14pt;\n"
"color:white;\n"
"}\n"
"")
        self.page_faculty_FroomNkey_contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_faculty_FroomNkey_contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_faculty_FroomNkey_contents.setObjectName("page_faculty_FroomNkey_contents")
        self.gridLayout_page_faculty_FroomNkey_contents = QtWidgets.QGridLayout(self.page_faculty_FroomNkey_contents)
        self.gridLayout_page_faculty_FroomNkey_contents.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_page_faculty_FroomNkey_contents.setSpacing(10)
        self.gridLayout_page_faculty_FroomNkey_contents.setObjectName("gridLayout_page_faculty_FroomNkey_contents")
        self.faculty_room1 = QtWidgets.QFrame(self.page_faculty_FroomNkey_contents)
        self.faculty_room1.setStyleSheet("QFrame {\n"
"border: 1px solid #69cdff;\n"
"border-radius: 6px;\n"
"}\n"
"")
        self.faculty_room1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_room1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_room1.setObjectName("faculty_room1")
        self.verticalLayout_faculty_room1 = QtWidgets.QVBoxLayout(self.faculty_room1)
        self.verticalLayout_faculty_room1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_room1.setSpacing(0)
        self.verticalLayout_faculty_room1.setObjectName("verticalLayout_faculty_room1")
        self.faculty_pushButton_room1 = QtWidgets.QPushButton(self.faculty_room1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faculty_pushButton_room1.sizePolicy().hasHeightForWidth())
        self.faculty_pushButton_room1.setSizePolicy(sizePolicy)
        self.faculty_pushButton_room1.setText("")
        self.faculty_pushButton_room1.setObjectName("faculty_pushButton_room1")
        self.verticalLayout_faculty_room1.addWidget(self.faculty_pushButton_room1)
        self.faculty_label_room1 = QtWidgets.QLabel(self.faculty_room1)
        self.faculty_label_room1.setStyleSheet("border: 0;\n"
"margin-left: 4px;")
        self.faculty_label_room1.setObjectName("faculty_label_room1")
        self.verticalLayout_faculty_room1.addWidget(self.faculty_label_room1)
        self.verticalLayout_faculty_room1.setStretch(0, 7)
        self.verticalLayout_faculty_room1.setStretch(1, 1)
        self.gridLayout_page_faculty_FroomNkey_contents.addWidget(self.faculty_room1, 2, 1, 1, 1)
        self.faculty_room2 = QtWidgets.QFrame(self.page_faculty_FroomNkey_contents)
        self.faculty_room2.setStyleSheet("QFrame {\n"
"border: 1px solid #69cdff;\n"
"border-radius: 6px;\n"
"}\n"
"")
        self.faculty_room2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_room2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_room2.setObjectName("faculty_room2")
        self.verticalLayout_faculty_room2 = QtWidgets.QVBoxLayout(self.faculty_room2)
        self.verticalLayout_faculty_room2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_room2.setSpacing(0)
        self.verticalLayout_faculty_room2.setObjectName("verticalLayout_faculty_room2")
        self.faculty_pushButton_room2 = QtWidgets.QPushButton(self.faculty_room2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faculty_pushButton_room2.sizePolicy().hasHeightForWidth())
        self.faculty_pushButton_room2.setSizePolicy(sizePolicy)
        self.faculty_pushButton_room2.setText("")
        self.faculty_pushButton_room2.setObjectName("faculty_pushButton_room2")
        self.verticalLayout_faculty_room2.addWidget(self.faculty_pushButton_room2)
        self.faculty_label_room2 = QtWidgets.QLabel(self.faculty_room2)
        self.faculty_label_room2.setStyleSheet("border: 0;\n"
"margin-left: 4px;")
        self.faculty_label_room2.setObjectName("faculty_label_room2")
        self.verticalLayout_faculty_room2.addWidget(self.faculty_label_room2)
        self.verticalLayout_faculty_room2.setStretch(0, 7)
        self.verticalLayout_faculty_room2.setStretch(1, 1)
        self.gridLayout_page_faculty_FroomNkey_contents.addWidget(self.faculty_room2, 2, 2, 1, 1)
        self.faculty_room3 = QtWidgets.QFrame(self.page_faculty_FroomNkey_contents)
        self.faculty_room3.setStyleSheet("QFrame {\n"
"border: 1px solid #69cdff;\n"
"border-radius: 6px;\n"
"}\n"
"")
        self.faculty_room3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_room3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_room3.setObjectName("faculty_room3")
        self.verticalLayout_faculty_room3 = QtWidgets.QVBoxLayout(self.faculty_room3)
        self.verticalLayout_faculty_room3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_room3.setSpacing(0)
        self.verticalLayout_faculty_room3.setObjectName("verticalLayout_faculty_room3")
        self.faculty_pushButton_room3 = QtWidgets.QPushButton(self.faculty_room3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faculty_pushButton_room3.sizePolicy().hasHeightForWidth())
        self.faculty_pushButton_room3.setSizePolicy(sizePolicy)
        self.faculty_pushButton_room3.setText("")
        self.faculty_pushButton_room3.setObjectName("faculty_pushButton_room3")
        self.verticalLayout_faculty_room3.addWidget(self.faculty_pushButton_room3)
        self.faculty_label_room3 = QtWidgets.QLabel(self.faculty_room3)
        self.faculty_label_room3.setStyleSheet("border: 0;\n"
"margin-left: 4px;")
        self.faculty_label_room3.setObjectName("faculty_label_room3")
        self.verticalLayout_faculty_room3.addWidget(self.faculty_label_room3)
        self.verticalLayout_faculty_room3.setStretch(0, 7)
        self.verticalLayout_faculty_room3.setStretch(1, 1)
        self.gridLayout_page_faculty_FroomNkey_contents.addWidget(self.faculty_room3, 2, 3, 1, 1)
        self.faculty_room5 = QtWidgets.QFrame(self.page_faculty_FroomNkey_contents)
        self.faculty_room5.setStyleSheet("QFrame {\n"
"border: 1px solid #69cdff;\n"
"border-radius: 6px;\n"
"}\n"
"")
        self.faculty_room5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_room5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_room5.setObjectName("faculty_room5")
        self.verticalLayout_faculty_room5 = QtWidgets.QVBoxLayout(self.faculty_room5)
        self.verticalLayout_faculty_room5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_room5.setSpacing(0)
        self.verticalLayout_faculty_room5.setObjectName("verticalLayout_faculty_room5")
        self.faculty_pushButton_room5 = QtWidgets.QPushButton(self.faculty_room5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faculty_pushButton_room5.sizePolicy().hasHeightForWidth())
        self.faculty_pushButton_room5.setSizePolicy(sizePolicy)
        self.faculty_pushButton_room5.setText("")
        self.faculty_pushButton_room5.setObjectName("faculty_pushButton_room5")
        self.verticalLayout_faculty_room5.addWidget(self.faculty_pushButton_room5)
        self.faculty_label_room5 = QtWidgets.QLabel(self.faculty_room5)
        self.faculty_label_room5.setStyleSheet("border: 0;\n"
"margin-left: 4px;")
        self.faculty_label_room5.setObjectName("faculty_label_room5")
        self.verticalLayout_faculty_room5.addWidget(self.faculty_label_room5)
        self.verticalLayout_faculty_room5.setStretch(0, 7)
        self.verticalLayout_faculty_room5.setStretch(1, 1)
        self.gridLayout_page_faculty_FroomNkey_contents.addWidget(self.faculty_room5, 4, 2, 1, 1)
        self.faculty_room4 = QtWidgets.QFrame(self.page_faculty_FroomNkey_contents)
        self.faculty_room4.setStyleSheet("QFrame {\n"
"border: 1px solid #69cdff;\n"
"border-radius: 6px;\n"
"}\n"
"")
        self.faculty_room4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_room4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_room4.setObjectName("faculty_room4")
        self.verticalLayout_faculty_room4 = QtWidgets.QVBoxLayout(self.faculty_room4)
        self.verticalLayout_faculty_room4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_room4.setSpacing(0)
        self.verticalLayout_faculty_room4.setObjectName("verticalLayout_faculty_room4")
        self.faculty_pushButton_room4 = QtWidgets.QPushButton(self.faculty_room4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faculty_pushButton_room4.sizePolicy().hasHeightForWidth())
        self.faculty_pushButton_room4.setSizePolicy(sizePolicy)
        self.faculty_pushButton_room4.setText("")
        self.faculty_pushButton_room4.setObjectName("faculty_pushButton_room4")
        self.verticalLayout_faculty_room4.addWidget(self.faculty_pushButton_room4)
        self.faculty_label_room4 = QtWidgets.QLabel(self.faculty_room4)
        self.faculty_label_room4.setStyleSheet("border: 0;\n"
"margin-left: 4px;")
        self.faculty_label_room4.setObjectName("faculty_label_room4")
        self.verticalLayout_faculty_room4.addWidget(self.faculty_label_room4)
        self.verticalLayout_faculty_room4.setStretch(0, 7)
        self.verticalLayout_faculty_room4.setStretch(1, 1)
        self.gridLayout_page_faculty_FroomNkey_contents.addWidget(self.faculty_room4, 4, 1, 1, 1)
        self.faculty_room6 = QtWidgets.QFrame(self.page_faculty_FroomNkey_contents)
        self.faculty_room6.setStyleSheet("QFrame {\n"
"border: 1px solid #69cdff;\n"
"border-radius: 6px;\n"
"}\n"
"")
        self.faculty_room6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.faculty_room6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.faculty_room6.setObjectName("faculty_room6")
        self.verticalLayout_faculty_room6 = QtWidgets.QVBoxLayout(self.faculty_room6)
        self.verticalLayout_faculty_room6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_faculty_room6.setSpacing(0)
        self.verticalLayout_faculty_room6.setObjectName("verticalLayout_faculty_room6")
        self.faculty_pushButton_room6 = QtWidgets.QPushButton(self.faculty_room6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faculty_pushButton_room6.sizePolicy().hasHeightForWidth())
        self.faculty_pushButton_room6.setSizePolicy(sizePolicy)
        self.faculty_pushButton_room6.setText("")
        self.faculty_pushButton_room6.setObjectName("faculty_pushButton_room6")
        self.verticalLayout_faculty_room6.addWidget(self.faculty_pushButton_room6)
        self.faculty_label_room6 = QtWidgets.QLabel(self.faculty_room6)
        self.faculty_label_room6.setStyleSheet("border: 0;\n"
"margin-left: 4px;")
        self.faculty_label_room6.setObjectName("faculty_label_room6")
        self.verticalLayout_faculty_room6.addWidget(self.faculty_label_room6)
        self.verticalLayout_faculty_room6.setStretch(0, 7)
        self.verticalLayout_faculty_room6.setStretch(1, 1)
        self.gridLayout_page_faculty_FroomNkey_contents.addWidget(self.faculty_room6, 4, 3, 1, 1)
        self.verticalLayout_page_faculty_FroomNkey.addWidget(self.page_faculty_FroomNkey_contents)
        self.verticalLayout_page_faculty_FroomNkey.setStretch(0, 20)
        self.verticalLayout_faculty_roomNkey_mainTab.addWidget(self.page_faculty_FroomNkey)
        self.tabWidget_faculty_roomNkey.addTab(self.faculty_roomNkey_mainTab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_faculty_roomNkey.addTab(self.tab_5, "")
        self.verticalLayout_page_roomNkey.addWidget(self.tabWidget_faculty_roomNkey)
        self.stackedWidget.addWidget(self.page_roomNkey)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_content)
        self.frame_grip = QtWidgets.QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_grip.setStyleSheet("background-color: rgba(37,39,77)")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_6.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_label_bottom = QtWidgets.QFrame(self.frame_grip)
        self.frame_label_bottom.setStyleSheet("background-color: rgba(37,39,77)")
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_credits = QtWidgets.QLabel(self.frame_label_bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits.setText("")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_7.addWidget(self.label_credits)
        self.label_version = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_7.addWidget(self.label_version)
        self.horizontalLayout_6.addWidget(self.frame_label_bottom)
        self.frame_size_grip = QtWidgets.QFrame(self.frame_grip)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_size_grip.setStyleSheet("QSizeGrip {\n"
"    background-image: url(:/16x16/icons/16x16/cil-size-grip.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"}\n"
"\n"
"QFrame{background-color: rgba(37,39,77);}")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_6.addWidget(self.frame_size_grip)
        self.verticalLayout_4.addWidget(self.frame_grip)
        self.horizontalLayout_2.addWidget(self.frame_content_right)
        self.verticalLayout.addWidget(self.frame_center)
        self.horizontalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_faculty_appnt.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_minimize, self.btn_maximize_restore)
        MainWindow.setTabOrder(self.btn_maximize_restore, self.btn_close)
        MainWindow.setTabOrder(self.btn_close, self.btn_toggle_menu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title_bar_top.setText(_translate("MainWindow", "Main Window - Base"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.label_top_info_2.setText(_translate("MainWindow", "| HOME"))
        self.label_user_icon.setText(_translate("MainWindow", "WM"))
        self.label_6.setText(_translate("MainWindow", "HOME"))
        self.label.setText(_translate("MainWindow", "Empyt Page - By: Wanderson M. Pimenta"))
        self.label_7.setText(_translate("MainWindow", "Page Index 0"))
        self.fac_avl_label.setText(_translate("MainWindow", "Availability"))
        self.day_avl_l1.setText(_translate("MainWindow", "Day/s Available"))
        self.time_avl_l1.setText(_translate("MainWindow", "Time/s Available"))
        self.queue_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Queue is Empty.</span></p></body></html>"))
        self.fac_FcontentRight_bot_Ltop.setText(_translate("MainWindow", "Logs"))
        self.tabWidget_faculty_appnt.setTabText(self.tabWidget_faculty_appnt.indexOf(self.fac_appnt_main), _translate("MainWindow", " Appointments "))
        self.tabWidget_faculty_appnt.setTabText(self.tabWidget_faculty_appnt.indexOf(self.fac_appnt_avl), _translate("MainWindow", " Availability "))
        self.fac_Fhistofappnts_Ltop.setText(_translate("MainWindow", "History of Appointments"))
        self.tabWidget_faculty_appnt.setTabText(self.tabWidget_faculty_appnt.indexOf(self.fac_appnt_histofappnts), _translate("MainWindow", " History "))
        self.faculty_ss_Fleft_tcreatedLabel.setText(_translate("MainWindow", "Tasks Created"))
        self.faculty_ss_right_Ftop_iconLabel.setText(_translate("MainWindow", "Task Icons"))
        self.faculty_ss_tcreationLabel.setText(_translate("MainWindow", "Task Creation"))
        self.faculty_ss_right_top_tcreation_right_okCreationButton.setText(_translate("MainWindow", "TC Done"))
        self.tabWidget_faculty_ss.setTabText(self.tabWidget_faculty_ss.indexOf(self.faculty_ss_mainTab), _translate("MainWindow", " Tasks "))
        self.tabWidget_faculty_ss.setTabText(self.tabWidget_faculty_ss.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.faculty_label_room1.setText(_translate("MainWindow", "Room 1"))
        self.faculty_label_room2.setText(_translate("MainWindow", "Room 2"))
        self.faculty_label_room3.setText(_translate("MainWindow", "Room 3"))
        self.faculty_label_room5.setText(_translate("MainWindow", "Room 5"))
        self.faculty_label_room4.setText(_translate("MainWindow", "Room 4"))
        self.faculty_label_room6.setText(_translate("MainWindow", "Room 6"))
        self.tabWidget_faculty_roomNkey.setTabText(self.tabWidget_faculty_roomNkey.indexOf(self.faculty_roomNkey_mainTab), _translate("MainWindow", " Room Reservation "))
        self.tabWidget_faculty_roomNkey.setTabText(self.tabWidget_faculty_roomNkey.indexOf(self.tab_5), _translate("MainWindow", "Tab 2"))
        self.label_version.setText(_translate("MainWindow", "v1.0.1"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
