# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pushbutton_context-menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


dayLex = {'Monday' : 0, 'Tuesday' : 1, 'Wednesday' : 2, 'Thursday' : 3, 'Friday' : 4, 'Saturday' : 5}
timeLex = {"7:30-9:00" : 0,"9:00-10:30" : 1,"10:30-12:00" : 2,"12:00-1:30" : 3,
            "1:30-3:00" : 4, "3:00-4:30" : 5, "4:30-6:00" : 6}

listofDaySelections = ['Tuesday','Thursday','Monday','Saturday','Friday']
listofDaySelections.sort(key=lambda x: dayLex[x])
print(listofDaySelections)

listofTimeSelections = ["3:00-4:30","9:00-10:30","4:30-6:00","12:00-1:30","7:30-9:00"]
listofTimeSelections.sort(key=lambda x: timeLex[x])
print(listofTimeSelections)




"""
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)

        ## PUSHBUTTON WITH POPUP MENU
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 70, 71, 21))
        self.pushButton.setObjectName("pushButton")


        self.popMenu = QtWidgets.QMenu()
        self.popMenu.setObjectName('popMenu')
        
        self.studAction = QtWidgets.QAction("Student")
        self.facAction = QtWidgets.QAction("Faculty")

        self.popMenu.addAction(self.studAction)
        self.popMenu.addAction(self.facAction)

        self.studAction.triggered.connect(lambda: print("Student Trigger"))
        self.facAction.triggered.connect(lambda: print("Faculty Trigger"))

 
        self.pushButton.setMenu(self.popMenu)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton")) 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
"""