# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pushbutton_context-menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)

        ## PUSHBUTTON WITH POPUP MENU
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 70, 71, 21))
        self.pushButton.setObjectName("pushButton")

        self.popMenu = QtWidgets.QMenu()
        self.pushButton.setObjectName('popMenu')
        
        self.studAction = QtWidgets.QAction("Student")
        self.facAction = QtWidgets.QAction("Faculty")

        self.studAction.triggered.connect(lambda: print("Student Trigger"))
        self.facAction.triggered.connect(lambda: print("Faculty Trigger"))

        self.popMenu.addAction(self.studAction)
        self.popMenu.addAction(self.facAction)

        

        self.pushButton.setMenu(self.popMenu)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton")) 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
