# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SS_studside.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(830, 616)
        Form.setStyleSheet("background-color: rgb(70, 72, 102);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_student_Fss = QtWidgets.QFrame(Form)
        self.page_student_Fss.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_student_Fss.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_student_Fss.setObjectName("page_student_Fss")
        self.horizontalLayout_page_student_Fss = QtWidgets.QHBoxLayout(self.page_student_Fss)
        self.horizontalLayout_page_student_Fss.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_page_student_Fss.setSpacing(18)
        self.horizontalLayout_page_student_Fss.setObjectName("horizontalLayout_page_student_Fss")
        self.page_student_ss_Fleft = QtWidgets.QFrame(self.page_student_Fss)
        self.page_student_ss_Fleft.setStyleSheet("QFrame{\n"
"border: 1px solid #69cdff;\n"
"border-radius: 10px;\n"
"}")
        self.page_student_ss_Fleft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_student_ss_Fleft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_student_ss_Fleft.setObjectName("page_student_ss_Fleft")
        self.verticalLayout_page_student_ss_Fleft = QtWidgets.QVBoxLayout(self.page_student_ss_Fleft)
        self.verticalLayout_page_student_ss_Fleft.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_page_student_ss_Fleft.setSpacing(6)
        self.verticalLayout_page_student_ss_Fleft.setObjectName("verticalLayout_page_student_ss_Fleft")
        self.student_ss_LavlTasks = QtWidgets.QLabel(self.page_student_ss_Fleft)
        self.student_ss_LavlTasks.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-size: 11pt;\n"
"border: 0;\n"
"margin-left: 4px;\n"
"}")
        self.student_ss_LavlTasks.setObjectName("student_ss_LavlTasks")
        self.verticalLayout_page_student_ss_Fleft.addWidget(self.student_ss_LavlTasks)
        self.student_scrollArea_ssLeft = QtWidgets.QScrollArea(self.page_student_ss_Fleft)
        self.student_scrollArea_ssLeft.setStyleSheet("QScrollArea{\n"
"border: 0;\n"
"}")
        self.student_scrollArea_ssLeft.setWidgetResizable(True)
        self.student_scrollArea_ssLeft.setObjectName("student_scrollArea_ssLeft")
        self.student_scrollAreaWidgetContents_ssLeft_contents = QtWidgets.QWidget()
        self.student_scrollAreaWidgetContents_ssLeft_contents.setGeometry(QtCore.QRect(0, 0, 386, 535))
        self.student_scrollAreaWidgetContents_ssLeft_contents.setObjectName("student_scrollAreaWidgetContents_ssLeft_contents")
        self.btn_task = QtWidgets.QPushButton(self.student_scrollAreaWidgetContents_ssLeft_contents)
        self.btn_task.setGeometry(QtCore.QRect(0, 70, 111, 51))
        self.btn_task.setToolTip("")
        self.btn_task.setStyleSheet("background-color: rgb(179, 179, 179);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/documentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_task.setIcon(icon)
        self.btn_task.setIconSize(QtCore.QSize(30, 30))
        self.btn_task.setObjectName("btn_task")
        self.btn_task_2 = QtWidgets.QPushButton(self.student_scrollAreaWidgetContents_ssLeft_contents)
        self.btn_task_2.setGeometry(QtCore.QRect(217, 70, 161, 51))
        self.btn_task_2.setStyleSheet("background-color: rgb(179, 179, 179);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/paperwork.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_task_2.setIcon(icon1)
        self.btn_task_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_task_2.setObjectName("btn_task_2")
        self.btn_task_3 = QtWidgets.QPushButton(self.student_scrollAreaWidgetContents_ssLeft_contents)
        self.btn_task_3.setGeometry(QtCore.QRect(114, 70, 101, 51))
        self.btn_task_3.setStyleSheet("background-color: rgb(179, 179, 179);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/assistant.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_task_3.setIcon(icon2)
        self.btn_task_3.setIconSize(QtCore.QSize(30, 30))
        self.btn_task_3.setObjectName("btn_task_3")
        self.btn_task_4 = QtWidgets.QPushButton(self.student_scrollAreaWidgetContents_ssLeft_contents)
        self.btn_task_4.setGeometry(QtCore.QRect(85, 130, 171, 51))
        self.btn_task_4.setStyleSheet("background-color: rgb(179, 179, 179);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/checking activities.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_task_4.setIcon(icon3)
        self.btn_task_4.setIconSize(QtCore.QSize(30, 30))
        self.btn_task_4.setObjectName("btn_task_4")
        self.student_scrollArea_ssLeft.setWidget(self.student_scrollAreaWidgetContents_ssLeft_contents)
        self.verticalLayout_page_student_ss_Fleft.addWidget(self.student_scrollArea_ssLeft)
        self.verticalLayout_page_student_ss_Fleft.setStretch(0, 1)
        self.verticalLayout_page_student_ss_Fleft.setStretch(1, 12)
        self.horizontalLayout_page_student_Fss.addWidget(self.page_student_ss_Fleft)
        self.page_student_ss_Fright = QtWidgets.QFrame(self.page_student_Fss)
        self.page_student_ss_Fright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_student_ss_Fright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_student_ss_Fright.setObjectName("page_student_ss_Fright")
        self.verticalLayout_page_student_ss_Fright = QtWidgets.QVBoxLayout(self.page_student_ss_Fright)
        self.verticalLayout_page_student_ss_Fright.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_page_student_ss_Fright.setSpacing(18)
        self.verticalLayout_page_student_ss_Fright.setObjectName("verticalLayout_page_student_ss_Fright")
        self.student_ss_taskInfo = QtWidgets.QFrame(self.page_student_ss_Fright)
        self.student_ss_taskInfo.setStyleSheet("QFrame{\n"
"border: 1px solid #69cdff;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QLabel{\n"
"color: white;\n"
"border: 0;\n"
"}")
        self.student_ss_taskInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_ss_taskInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_ss_taskInfo.setObjectName("student_ss_taskInfo")
        self.verticalLayout_student_ss_taskInfo = QtWidgets.QVBoxLayout(self.student_ss_taskInfo)
        self.verticalLayout_student_ss_taskInfo.setContentsMargins(10, 10, 10, 8)
        self.verticalLayout_student_ss_taskInfo.setObjectName("verticalLayout_student_ss_taskInfo")
        self.stackedWidget = QtWidgets.QStackedWidget(self.student_ss_taskInfo)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.tDescription = QtWidgets.QTextEdit(self.page1)
        self.tDescription.setGeometry(QtCore.QRect(10, 10, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.tDescription.setFont(font)
        self.tDescription.setObjectName("tDescription")
        self.tHours = QtWidgets.QLabel(self.page1)
        self.tHours.setGeometry(QtCore.QRect(20, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.tHours.setFont(font)
        self.tHours.setObjectName("tHours")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.tHours_2 = QtWidgets.QLabel(self.page2)
        self.tHours_2.setGeometry(QtCore.QRect(20, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.tHours_2.setFont(font)
        self.tHours_2.setObjectName("tHours_2")
        self.tDescription_2 = QtWidgets.QTextEdit(self.page2)
        self.tDescription_2.setGeometry(QtCore.QRect(10, 10, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.tDescription_2.setFont(font)
        self.tDescription_2.setObjectName("tDescription_2")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.tHours_3 = QtWidgets.QLabel(self.page3)
        self.tHours_3.setGeometry(QtCore.QRect(20, 140, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.tHours_3.setFont(font)
        self.tHours_3.setObjectName("tHours_3")
        self.tDescription_3 = QtWidgets.QTextEdit(self.page3)
        self.tDescription_3.setGeometry(QtCore.QRect(10, 10, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.tDescription_3.setFont(font)
        self.tDescription_3.setObjectName("tDescription_3")
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.tHours_4 = QtWidgets.QLabel(self.page4)
        self.tHours_4.setGeometry(QtCore.QRect(20, 140, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.tHours_4.setFont(font)
        self.tHours_4.setObjectName("tHours_4")
        self.tDescription_4 = QtWidgets.QTextEdit(self.page4)
        self.tDescription_4.setGeometry(QtCore.QRect(10, 10, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.tDescription_4.setFont(font)
        self.tDescription_4.setObjectName("tDescription_4")
        self.stackedWidget.addWidget(self.page4)
        self.verticalLayout_student_ss_taskInfo.addWidget(self.stackedWidget)
        self.verticalLayout_page_student_ss_Fright.addWidget(self.student_ss_taskInfo)
        self.student_ss_currentTasks = QtWidgets.QFrame(self.page_student_ss_Fright)
        self.student_ss_currentTasks.setStyleSheet("QFrame{\n"
"border: 1px solid #69cdff;\n"
"border-radius: 10px;\n"
"}")
        self.student_ss_currentTasks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_ss_currentTasks.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_ss_currentTasks.setObjectName("student_ss_currentTasks")
        self.verticalLayout_student_ss_currentTasks = QtWidgets.QVBoxLayout(self.student_ss_currentTasks)
        self.verticalLayout_student_ss_currentTasks.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_student_ss_currentTasks.setSpacing(6)
        self.verticalLayout_student_ss_currentTasks.setObjectName("verticalLayout_student_ss_currentTasks")
        self.student_ss_LcurrentTasks = QtWidgets.QLabel(self.student_ss_currentTasks)
        self.student_ss_LcurrentTasks.setStyleSheet("QLabel{\n"
"color: white;\n"
"font-size: 11pt;\n"
"border: 0;\n"
"margin-left: 4px;\n"
"}")
        self.student_ss_LcurrentTasks.setObjectName("student_ss_LcurrentTasks")
        self.verticalLayout_student_ss_currentTasks.addWidget(self.student_ss_LcurrentTasks)
        self.student_scrollArea_sscurrentTasks = QtWidgets.QScrollArea(self.student_ss_currentTasks)
        self.student_scrollArea_sscurrentTasks.setStyleSheet("QScrollArea{\n"
"border: 0;\n"
"}")
        self.student_scrollArea_sscurrentTasks.setWidgetResizable(True)
        self.student_scrollArea_sscurrentTasks.setObjectName("student_scrollArea_sscurrentTasks")
        self.student_scrollArea_sscurrentTasks_contents = QtWidgets.QWidget()
        self.student_scrollArea_sscurrentTasks_contents.setGeometry(QtCore.QRect(0, 0, 384, 340))
        self.student_scrollArea_sscurrentTasks_contents.setObjectName("student_scrollArea_sscurrentTasks_contents")
        self.btn_ok = QtWidgets.QPushButton(self.student_scrollArea_sscurrentTasks_contents)
        self.btn_ok.setGeometry(QtCore.QRect(300, 310, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.btn_ok.setFont(font)
        self.btn_ok.setStyleSheet("QPushButton{\n"
"background-color: rgb(200, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"color:#333;\n"
"border-radius:10px;\n"
"background:#49ebff;\n"
"}")
        self.btn_ok.setObjectName("btn_ok")
        self.student_scrollArea_sscurrentTasks.setWidget(self.student_scrollArea_sscurrentTasks_contents)
        self.verticalLayout_student_ss_currentTasks.addWidget(self.student_scrollArea_sscurrentTasks)
        self.verticalLayout_student_ss_currentTasks.setStretch(0, 1)
        self.verticalLayout_student_ss_currentTasks.setStretch(1, 12)
        self.verticalLayout_page_student_ss_Fright.addWidget(self.student_ss_currentTasks)
        self.verticalLayout_page_student_ss_Fright.setStretch(0, 1)
        self.verticalLayout_page_student_ss_Fright.setStretch(1, 2)
        self.horizontalLayout_page_student_Fss.addWidget(self.page_student_ss_Fright)
        self.verticalLayout.addWidget(self.page_student_Fss)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.student_ss_LavlTasks.setText(_translate("Form", "Available Tasks"))
        self.btn_task.setText(_translate("Form", "Documentation"))
        self.btn_task_2.setText(_translate("Form", "Paperwork"))
        self.btn_task_3.setText(_translate("Form", "Assistant"))
        self.btn_task_4.setText(_translate("Form", "Checking Activity"))
        self.tDescription.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Century Gothic\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#d9d9d9;\">Making of Report, Saving important Documents, Importing and Exporting of files </span></p></body></html>"))
        self.tHours.setText(_translate("Form", "Credit: 5 Hours"))
        self.tHours_2.setText(_translate("Form", "Credit: 9 Hours"))
        self.tDescription_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Century Gothic\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; color:#f8f8f8;\">Assist the Teacher\'s in doing their non-teaching related chores like arranging their desk and other things and assist the Teachers, Students and Parent during enrollment</span></p></body></html>"))
        self.tHours_3.setText(_translate("Form", "Credit: 10 Hours"))
        self.tDescription_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Century Gothic\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#f8f8f8;\">Arranging of Papers in a certain order and filing them or Preparing the exam papers</span></p></body></html>"))
        self.tHours_4.setText(_translate("Form", "Credit: 11 Hours"))
        self.tDescription_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Century Gothic\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#f8f8f8;\">Checking of papers like exam papers, test papers and review papers</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.student_ss_LcurrentTasks.setText(_translate("Form", "Current Tasks"))
        self.btn_ok.setText(_translate("Form", "OK"))
import image_rc
